spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10

  datasource:
    url: jdbc:h2:mem:travel
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    spring:
      jpa:
        properties:
          hibernate:
            format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace